[package]
name = "joinproxy"
version = "2.0.1"
description = "Utilities to use IC together with Joining Proxy"
repository = "https://github.com/vporton/joining-proxy-rust"
keywords = [
  "proxy",
  "HTTP",
  "outcalls",
  "IC",
  "ICP",
  "Internet",
  "Computer"
]
license = "MIT"

[dependencies]
sha2 = "0.0.6"
xtended-numbers = "0.2.1"
core = "1.0.0"